config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users, only: [:show]
  resources :sessions, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	private
	def current_user
		@current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password_digest])
      session[:current_user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:notice] = "Something went wrong haha"
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@start_of_week = start_of_week
		@user = User.find(params[:id])
		if !current_user_profile?
			flash[:notice] = "not allowed bitch"
			redirect_to root_url
		end
	end

	private
	def current_user_profile?
		@user == current_user
	end

	def start_of_week
		Date.today.beginning_of_week
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<body>
   <%= form_with url: sessions_path do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.text_field :password_digest %>

      <%= f.submit "Login" %>
   <% end %>

   <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
   <% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mtp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.erb
<h1> <%= @user.name %> </h1>
<body>
    <% (0...6).each do |i| %>
       <%= (@start_of_week + i).strftime("%A, %d %B %Y") %></br >
    <% end %>
</body>